### PR TITLE
Adding normal prior functionality

### PR DESCRIPTION
**Pull request by andrewg3311**
Hey all,
Here are the files that execute the regular normal prior functionality (estimate mu and a). The functions mirror the structure of the existing "_point_normal" functions, for consistency.

### CODE REVIEW

**Comment by willwerscheid** [comment]
@andrewg3311 A few quick comments: 1. There's a lot of cutting-and-pasting here. Could you please think about how to rewrite these functions to re-use existing code (modifying existing code where necessary)? Otherwise these functions will become very difficult to maintain. 2. There was already a function called `ebnm_normal`. Now there are two. The old one should be removed (but look at the old one for an example of how to re-use code). 3. Please add unit tests when adding new functionality. I will admit that the coverage is poor right now, but that's no excuse to make it worse!

**Comment by andrewg3311** [comment]
@willwerscheid 
1) Can do. My first thought was to try to use the existing functions, but as they were, it didn't make sense. If I'm "allowed" to change existing functions, then I will try to re-work existing functions to be more general where needed, re-write my functions to call existing ones, etc.
2) I assumed that function would be removed, since it would be superseded by whatever functions I would write
3) Sure. It looked like there were only unit tests for the simpler functions (e.g. gradient calculations), since unit testing for the optimization is difficult. Do you have any suggestions on what I should/shouldn't add unit tests for?

**Comment by willwerscheid** [comment]
@andrewg3311 Yes, please feel free to modify existing functions. I am happy to take a look at any changes. We have not been good about writing tests for this package. I will try to add some for the point normal case over the next few days. One idea would be to simulate data from a known prior and then check that `ebnm` estimates something similar. But the main principle should be to test the interface (`ebnm_normal`, `ebnm_point_normal`), not so much the internal functions (calculating likelihoods, gradients, etc.).

**Comment by pcarbo** [comment]
Would it make most sense to create new branch in the main repository (e.g., `regular-normal`) for Andrew to explore these ideas? To do so, I would have to add him as a collaborator on this repo. 

I agree with the approach. It makes most sense to be confident that the implementation works and does the right thing before figuring out how to best integrate with the rest of the package functionality.

**Comment by stephens999** [comment]
yes, i like that idea.
Matthew

**Comment by pcarbo** [comment]
@andrewg3311 I've added you as a collaborator to this repo. If you are not sure how to create a new branch, I can do it for you, or explain how.

**Comment by andrewg3311** [comment]
@pcarbo I believe I just added the branch. Please check to make sure I did it right. Thanks!

**Comment by pcarbo** [comment]
@andrewg3311 Try committing a change to a file in that branch and pushing that change.

**Comment by andrewg3311** [comment]
@pcarbo Just tested it, looks to me like it's working (as is the Slack plugin you set up)

**Comment by pcarbo** [comment]
@andrewg3311 Looks good!

**Pull request closed without merging**
